# Generated by Django 5.1.7 on 2025-04-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_providerprofile_seekerprofile_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='email',
            field=models.CharField(default='dummy@example.com', max_length=30),
            preserve_default=False,
        ),
    ]
