# Generated by Django 5.1.7 on 2025-04-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_providerprofile_active_providerprofile_rating_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
