# Generated by Django 5.1.7 on 2025-04-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_seekerprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
