# Generated by Django 5.1.7 on 2025-04-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_seekerprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerprofile',
            name='active',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='total_rating',
        ),
    ]
