# Generated by Django 5.1.7 on 2025-04-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_providerprofile_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=10),
        ),
    ]
